### ISSUE TITLE
Fails to build with HDF 4.4.0

### ISSUE THREAD

**Issue by sebastic** [fhs/pyhdf#87]
As reported in [Debian Bug #1146659](https://bugs.debian.org/1146659):
> Your package FTBFS with HDF 4.4.0:
> ```
> pyhdf/hdfext_wrap.c: In function '_wrap_Vgetname':
> pyhdf/hdfext_wrap.c:9660:19: error: too few arguments to function 'Vgetname'; expected 3, have 2
>  9660 |   result = (int32)Vgetname(arg1,arg2);
>       |                   ^~~~~~~~
> /usr/include/hdf/hproto.h:1405:15: note: declared here
>  1405 | HDFLIBAPI int Vgetname(int32 vkey, char *vgname, size_t *buf_size);
>       |               ^~~~~~~~
> pyhdf/hdfext_wrap.c: In function '_wrap_Vgetclass':
> pyhdf/hdfext_wrap.c:9723:19: error: too few arguments to function 'Vgetclass'; expected 3, have 2
>  9723 |   result = (int32)Vgetclass(arg1,arg2);
>       |                   ^~~~~~~~~
> /usr/include/hdf/hproto.h:1407:15: note: declared here
>  1407 | HDFLIBAPI int Vgetclass(int32 vkey, char *vgclass, size_t *buf_size);
>       |               ^~~~~~~~~
> ```
> The full buildlog is attached.
> [python-hdf4_0.11.7-2.1_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1146659;filename=python-hdf4_0.11.7-2.1_amd64.build;msg=5)
